// entry point for our server.
var app = require('./server/server');
var colors = require('colors/safe');

app.listen(3000, function () {
  console.log(colors.rainbow('----------------------------  o8o  ----------------------------'));
  console.log('');
  console.log(colors.green('      ---------------------------------------------'));
  console.log(colors.green('     |   Hi there kind people of Catalytic!        |'));
  console.log(colors.green('      ---------------------------------------------'));
  console.log(colors.green('                                   /          '));
  console.log(colors.green('                                  /          '));
  console.log(colors.green('                             _____'));
  console.log(colors.green('                            |     |'));
  console.log(colors.green('                            | | | |'));
  console.log(colors.green('                            |_____|'));
  console.log(colors.green('                      ____ ___|_|___ ____'));
  console.log(colors.green('                     ()___)         ()___)'));
  console.log(colors.green('                     // /|  PUSHBOT  |\\ \\\\'));
  console.log(colors.green('                    // / |           | \\ \\\\'));
  console.log(colors.green('                   (___) |___________| (___)'));
  console.log(colors.green('                   (___)   (_______)   (___)'));
  console.log(colors.green('                   (___)     (___)     (___)'));
  console.log(colors.green('                   (___)      |_|      (___)'));
  console.log(colors.green('                   (___)  ___/___\\___   | |'));
  console.log(colors.green('                    | |  |           |  | |'));
  console.log(colors.green('                    | |  |___________| /___\\'));
  console.log(colors.green('                   /___\\  |||     ||| //   \\\\'));
  console.log(colors.green('                  //   \\\\ |||     ||| \\\\   //'));
  console.log(colors.green('                  \\\\   // |||     |||  \\\\ //'));
  console.log(colors.green('                   \\\\ // ()__)   (__()'));
  console.log(colors.green('                         ///       \\\\\\'));
  console.log(colors.green('                        ///         \\\\\\'));
  console.log(colors.green('                      _///___     ___\\\\\\_'));
  console.log(colors.green('                     |_______|   |_______|'));
  console.log('');
  console.log(colors.blue('Please vist'));
  console.log(colors.bold.blue.underline('http://localhost:3000/'));
  console.log(colors.blue('in your favorite browser!'));
  console.log('');
  console.log(colors.rainbow('----------------------------  o8o  ----------------------------'));
});
