// Process
export const GET_PROCESS_SUCCESS = 'GET_PROCESS_SUCCESS';
export const GET_PROCESS_FAILED = 'GET_PROCESS_FAILED';
export const UPDATE_PROCESS_DISPLAY_NAME = 'UPDATE_PROCESS_DISPLAY_NAME';
export const UPDATE_PROCESS_DESCRIPTION = 'UPDATE_PROCESS_DESCRIPTION';

// Steps
export const GET_STEPS_SUCCESS = 'GET_STEPS_SUCCESS';
export const GET_STEPS_FAILED = 'GET_STEPS_FAILED';
export const UPDATE_STEPS_DISPLAY_NAME = 'UPDATE_STEPS_DISPLAY_NAME';
export const UPDATE_STEPS_DESCRIPTION = 'UPDATE_STEPS_DESCRIPTION';

// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
